site_name: Radix Contribution Guide
pages:
- Home:
    - 'Welcome': 'index.md'
- Development:
    - 'development/getting-started.md'
    - 'development/workflow.md'
- Art:
    - 'art/graphics.md'
    - 'art/music.md'
